# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 13:28
from __future__ import unicode_literals

import core.orm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(blank=True, max_length=100, null=True)),
                ('since', models.CharField(blank=True, max_length=100, null=True)),
                ('secretariat', models.TextField(blank=True, null=True)),
                ('leader', models.CharField(blank=True, max_length=100, null=True)),
                ('slogan', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload Logo klub', null=True, upload_to='club/logo')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='orm.City')),
            ],
            options={
                'db_table': 'club',
                'ordering': ['register_number'],
            },
        ),
        migrations.CreateModel(
            name='ClubFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.orm.models.file_club)),
                ('thumbnail', models.ImageField(default=None, upload_to=core.orm.models.file_club_thumbnail)),
                ('filename', models.CharField(default=None, max_length=30)),
                ('file_ext', models.CharField(default=None, max_length=30)),
                ('mimetype', models.CharField(default=None, max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubfiles', to='orm.Club')),
            ],
            options={
                'db_table': 'club_files',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('draw_length', models.CharField(blank=True, max_length=5, null=True)),
                ('position', models.CharField(blank=True, max_length=25, null=True)),
                ('picture', models.ImageField(blank=True, default='user/avatar.png', help_text='Upload Potomu sebagai gambar profile', null=True, upload_to=core.orm.models.file_profile)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='orm.Club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='MemberFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.orm.models.file_member)),
            ],
            options={
                'db_table': 'member_files',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='orm.Club')),
            ],
            options={
                'db_table': 'social',
            },
        ),
    ]
