# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubfiles',
            name='thumbnail',
        ),
    ]
